const GET_SOLO_RANKS = 'GET_SOLO_RANKS';
const GET_DUO_RANKS = 'GET_DUO_RANKS';
const GET_QUEUE = 'GET_QUEUE';
const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
const GET_TOURNAMENT = 'GET_TOURNAMENT';
const GET_TOURNAMENT_REGISTRATION_LIST = 'GET_TOURNAMENT_REGISTRATION_LIST';
const ADD_USER_TO_TOURNAMENT = 'ADD_USER_TO_TOURNAMENT';
const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
const EXIT_FROM_QUEUE = 'EXIT_FROM_QUEUE';
const START = 'START';
const MOVE_DOWN_QUEUE = 'MOVE_DOWN_QUEUE';
const WIN = 'WIN';
const CHANGE_MODE = 'CHANGE_MODE';
const DUO_ADD_TO_QUEUE = 'DUO_ADD_TO_QUEUE';
const DUO_EXIT_FROM_QUEUE = 'DUO_EXIT_FROM_QUEUE';
const DUO_JOIN_PAIR_QUEUE = 'DUO_JOIN_PAIR_QUEUE';
const DUO_MOVE_DOWN_QUEUE = 'DUO_MOVE_DOWN_QUEUE';
const DUO_WIN_QUEUE = 'DUO_WIN_QUEUE';

module.exports = {
  GET_SOLO_RANKS,
  GET_DUO_RANKS,
  GET_QUEUE,
  GET_TOURNAMENTS,
  GET_TOURNAMENT,
  GET_TOURNAMENT_REGISTRATION_LIST,
  ADD_USER_TO_TOURNAMENT,
  ADD_TO_QUEUE,
  EXIT_FROM_QUEUE,
  START,
  MOVE_DOWN_QUEUE,
  WIN,
  CHANGE_MODE,
  DUO_ADD_TO_QUEUE,
  DUO_EXIT_FROM_QUEUE,
  DUO_JOIN_PAIR_QUEUE,
  DUO_MOVE_DOWN_QUEUE,
  DUO_WIN_QUEUE,
};
